name: Chore
description: Refactor, infra, deps, docs, tooling
title: "[Chore]: "
labels: ["chore"]
body:
  - type: textarea
    id: what
    attributes:
      label: What
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of done
      value: |
        - [ ] 
        - [ ]
